#FROM nikolaik/python-nodejs:latest
#FROM nyukers/sunhose:mezgoodle
#FROM alpine:latest
#FROM nyukers/sunhose:aformat
#FROM nikolaik/python-nodejs:latest
FROM nyukers/sunhose:mezgoodle
MAINTAINER mezgoodle <mezgoodle@gmail.com>

RUN "/python.sh"
