# FROM nikolaik/python-nodejs:latest
FROM alpine:latest
# FROM nyukers/sunhose:aformat
MAINTAINER mezgoodle <mezgoodle@gmail.com>

RUN apk add jq bash git npm py-pip nodejs python3
# WORKDIR /app
COPY test.sh /test.sh
RUN chmod +x /test.sh
ENTRYPOINT ["/test.sh"]

# RUN tree -L 1
RUN echo "Hello world"
# CMD ["/gitstart.sh"]
